const services=[
{name:'Korean Lash Lift ✨',price:80,time:'60+ min',cat:'lashes',desc:'A gentle Korean-inspired lift designed to raise natural lashes from the root for a clean, lifted look.'},
{name:'Full Lash Set 🖤',price:100,time:'120 min',cat:'lashes',deposit:20,desc:'Classic, hybrid, volume or wispy lash set customized to your preferred style.'},
{name:'2 Week Lash Fill 🖤',price:70,time:'90 min',cat:'lashes',deposit:20,desc:'For appointments 14 days after your last lash service. At least 40% of extensions must remain.'},
{name:'3 Week Lash Fill 🖤',price:85,time:'90 min',cat:'lashes',deposit:20,desc:'For appointments 21 days after your last lash service. At least 40% of extensions must remain.'},
{name:'Mini Lash Fill 🖤',price:40,time:'90 min',cat:'lashes',deposit:20,desc:'A one-week fill for clients who love to keep their lashes looking extra full.'},
{name:'Foreign Fill',price:90,time:'90 min',cat:'lashes',desc:'Lash fill service for qualifying extension work originally applied by another artist.'},
{name:'Colored Lash',price:10,time:'10 min',cat:'lashes',desc:'Add a pop of color to your lash look. Ask about available shades.'},
{name:'Lash Removal',price:35,time:'45 min',cat:'lashes',deposit:20,desc:'Professional removal of existing lash extensions.'},
{name:'Custom Facial 🫧',price:60,time:'55 min',cat:'skin',deposit:20,desc:'A personalized facial experience designed to refresh your skin and create a relaxing reset.'},
{name:'Brazilian',price:55,time:'30 min',cat:'wax',desc:'Professional Brazilian waxing service.'},
{name:'Upper Lip Wax',price:10,time:'15 min',cat:'wax',desc:'Quick upper-lip waxing for a smooth, clean finish.'},
{name:'Under Arm Wax',price:25,time:'25 min',cat:'wax',desc:'Underarm waxing service for smooth, longer-lasting results.'},
{name:'Brow Shape',price:20,time:'30 min',cat:'brows',desc:'Customized brow shaping designed around your natural brow and facial features.'},
{name:'Brow Tint',price:30,time:'30 min',cat:'brows',desc:'Semi-permanent brow tint to enhance definition and create a fuller-looking brow.'},
{name:'Tooth Gem ❄️💎',price:35,time:'20 min',cat:'gems',desc:'Swarovski crystal tooth gems with select shapes such as hearts, stars and flowers.'}
];
const grid=document.getElementById('serviceGrid');let cart=[];
function render(filter='all'){grid.innerHTML=services.filter(s=>filter==='all'||s.cat===filter).map((s,i)=>`<article class="serviceCard"><div><div class="serviceTop"><h3>${s.name}</h3><span class="price">$${s.price}${s.name.includes('Korean')?'+':''}</span></div><p>${s.desc}</p><div class="meta">${s.time}${s.deposit?` · $${s.deposit} deposit required`:''}</div></div><button class="addBtn" data-name="${s.name}">Add to Bag +</button></article>`).join('');document.querySelectorAll('.addBtn').forEach(b=>b.onclick=()=>add(b.dataset.name))}
render();document.querySelectorAll('.filters button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.filters button').forEach(x=>x.classList.remove('active'));b.classList.add('active');render(b.dataset.filter)});
function add(name){if(!cart.includes(name))cart.push(name);updateCart();openCart()}function updateCart(){document.getElementById('cartCount').textContent=cart.length;const box=document.getElementById('cartItems');box.innerHTML=cart.length?cart.map(n=>{const s=services.find(x=>x.name===n);return `<div class="cartItem"><div><b>${s.name}</b><div>$${s.price}</div></div><button data-remove="${s.name}">Remove</button></div>`}).join(''):'<p>Your bag is empty.</p>';document.getElementById('cartTotal').textContent='$'+cart.reduce((a,n)=>a+services.find(s=>s.name===n).price,0);document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{cart=cart.filter(n=>n!==b.dataset.remove);updateCart()})}
const cartEl=document.getElementById('cart'),overlay=document.getElementById('overlay');function openCart(){cartEl.classList.add('open');overlay.classList.add('open')}function closeCart(){cartEl.classList.remove('open');overlay.classList.remove('open')}document.getElementById('cartBtn').onclick=openCart;document.getElementById('closeCart').onclick=closeCart;overlay.onclick=closeCart;
const imgs=Array.from({length:9},(_,i)=>`assets/gallery-${String(i+1).padStart(2,'0')}.png`);const gg=document.getElementById('galleryGrid');gg.innerHTML=imgs.map((src,i)=>`<div class="galleryItem" data-i="${i}"><img src="${src}" alt="Amo Amore beauty work ${i+1}" loading="lazy"></div>`).join('');let current=0;const lb=document.getElementById('lightbox'),lbImg=document.getElementById('lightboxImg');function show(i){current=(i+imgs.length)%imgs.length;lbImg.src=imgs[current];document.getElementById('lbCounter').textContent=`${current+1} / ${imgs.length}`;lb.classList.add('open')}document.querySelectorAll('.galleryItem').forEach(el=>el.onclick=()=>show(+el.dataset.i));document.getElementById('prevLb').onclick=()=>show(current-1);document.getElementById('nextLb').onclick=()=>show(current+1);document.getElementById('closeLb').onclick=()=>lb.classList.remove('open');document.addEventListener('keydown',e=>{if(!lb.classList.contains('open'))return;if(e.key==='ArrowRight')show(current+1);if(e.key==='ArrowLeft')show(current-1);if(e.key==='Escape')lb.classList.remove('open')});
document.querySelector('.menu').onclick=()=>document.querySelector('.nav nav').classList.toggle('open');document.querySelectorAll('.nav nav a').forEach(a=>a.addEventListener('click',()=>document.querySelector('.nav nav').classList.remove('open')));
document.getElementById('contactForm').onsubmit=e=>{e.preventDefault();document.getElementById('formMsg').textContent='Thanks! This demo form is ready to be connected to the owner email or a form service after launch.';e.target.reset()};
